title: Datalink Cloud Dashboard
datetime: '%A, %b %d %Y %I:%M:%S %p'
apps:
  - name: Traefik
    icon: https://api.iconify.design/bi/bell-fill.svg
    url: https://traefik.example.com
    category: server-management
  - name: Portainer
    icon: docker
    url: https://portainer.example.com
    tab: true
    category: server-management
  - name: TailScale
    icon: vpn
    url: https://tailscale.example.com/web
    tab: true
    category: device-management
  - name: Unifi
    icon: access-point-network
    url: https://unifi.example.com
    tab: true
    category: device-management
  - name: Knowledge Base
    icon: lightbulb-on
    url: https://kb.example.com
    tab: true
    category: utilities
  - name: VaultWarden
    icon: form-textbox-password
    url: https://vault.example.com
    tab: true
    category: utilities
  - name: Draw.io
    icon: lead-pencil
    url: https://draw.example.com
    tab: true
    category: utilities
  - name: TimeTagger
    icon: calendar-clock-outline
    url: https://time.example.com
    tab: true
    category: utilities
  - name: RSS
    icon: rss-box
    url: https://rss.example.com
    tab: true
    category: utilities
bookmarks:
  - name: Azure Portal
    url: https://portal.azure.com
    category: microsoft
  - name: Microsoft Admin
    url: https://admin.microsoft.com
    category: microsoft
  - name: Entra Admin
    url: https://entra.microsoft.com
    category: microsoft
  - name: Barracuda Downloads
    url: https://dlportal.barracudanetworks.com
    category: firewalls
